name: 'Kingly page'
type: 'Site'
description: Configures a Kingly text paragraph.
recipes:
  - core/recipes/basic_html_format_editor

install:
  - paragraphs
  - layout_paragraphs
  - pathauto

config:
  strict: false
